route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram'

  routes:
    - receiver: 'telegram'
      group_wait: 10s
      match_re:
        severity: critical
      continue: true

    - receiver: 'web.hook'
      group_wait: 10s
      match_re:
        severity: warning
      continue: true

receivers:
  - name: 'telegram'
    telegram_configs:
    - chat_id: 
      parse_mode: 'Markdown'
      bot_token: ''
      message: <tmpl_string> default = 'Node down'   
      send_resolved: true

  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001'
        send_resolved: true
        max_alerts: 5